version: '2.1'

services:

  dns: 
    image: coredns/coredns
    restart: always
    command: -conf coredns-config/Corefile
    ports:
      - 53:53/udp
    volumes:
      - ./config:/coredns-config/  
    labels:
      - "traefik.enable=false"      
    networks:       
      - dns
      
networks:   
  dns:      
