version: '2.1'

services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    extra_hosts: 
      - "gitlab.example.com:172.17.0.1"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'     
        registry_external_url 'http://registry.example.com' 
        gitlab_rails['gitlab_shell_ssh_port'] = 2224    
        registry['enable'] = true
        gitlab_rails['registry_api_url'] = "http://registry:5000"        
    ports: 
      - "2224:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks: 
      - proxy  
      - gitlab
    labels:
      - "traefik.docker.network=reverseproxy_proxy"  
      - "traefik.gitlab.backend=gitlab"            
      - "traefik.gitlab.port=80"      
      - "traefik.gitlab.frontend.rule=Host:gitlab.example.com"
      - "traefik.registry.backend=registry"      
      - "traefik.registry.port=80"      
      - "traefik.registry.frontend.rule=Host:registry.example.com"


  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    extra_hosts: 
      - "gitlab.example.com:172.17.0.1" 
    environment: 
      - CI_SERVER_URL=http://gitlab/
      - RUNNER_TOKEN=VfP3skup5sKsotR_z83c
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - proxy  
      - gitlab          

  registry:
    image: registry:2
    restart: always
    environment: 
      REGISTRY_STORAGE_DELETE_ENABLED: "true"    
    volumes:
      - registry-data:/var/lib/registry            
    networks:       
      - gitlab
    labels:  
      - "traefik.enable=false"      


volumes:
  gitlab-config:
  gitlab-logs:       
  gitlab-data:   
  gitlab-runner-config:
  registry-data:     

networks: 
  proxy:      
    external:
      name: reverseproxy_proxy
  gitlab:
